version: "3.9"
services:
  aleph-tezos-indexer:
    platform: linux/amd64
    container_name: aleph-tezos-indexer
    build:
      context: ../
      dockerfile: docker/Dockerfile
    # restart: unless-stopped
    restart: no
    ports:
      - 8090:8000
    # environment:
    #   - DB_FOLDER=/data
    #   - RPC_ENDPOINT=__ENDPOINT_A__
    #   - TRUSTED_RPC_ENDPOINT=__ENDPOINT_B__
    #   - WELL_CONTRACT=__OPTIONAL__WELL_CONTRACT__ADDRESS__
    #   - UNTIL_BLOCK=__UNTIL_BLOCK__
    #   - PORT=8000
    #   - CONCURRENT_JOB=10
    #   - BATCH_SIZE=50
